# Generated by Django 3.0.5 on 2026-05-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
